name: up version package

on: 
  pull_request:
  
jobs:
  up_version:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: UP version(patch)
        run: npm version patch --no-git-tag-version
          
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package version
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ME }}
    
