name: NPM Publish

on: [workflow_dispatch]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: rm -rf .github

      - name: npm install and build
        run: |
          npm install
          npm run validator
          npm run build --if-present
        env:
          CI: true

      - name: npm deploy
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
