name: NPM Publish

on:
  workflow_run:
    workflows: ["bump"]
    branches: ["master"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm build
        run: |
          npm ci
          npm run validator
          npm run build --if-present
        env:
          CI: true

      - name: npm deploy
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
